## 图像基本操作

#### 环境配置地址：

- Anaconda:https://www.anaconda.com/download/

- Python_whl:https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv

- eclipse:按照自己的喜好，选择一个能debug就好

![title](lena_img.png)

### 数据读取-图像

- cv2.IMREAD_COLOR：彩色图像
- cv2.IMREAD_GRAYSCALE：灰度图像

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np 
%matplotlib inline 
# opencv读取的格式是BGR
img=cv2.imread('cat.jpg')

In [2]:
img

array([[[142, 151, 160],
        [146, 155, 164],
        [151, 160, 170],
        ...,
        [156, 172, 185],
        [155, 171, 184],
        [154, 170, 183]],

       [[108, 117, 126],
        [112, 123, 131],
        [118, 127, 137],
        ...,
        [155, 171, 184],
        [154, 170, 183],
        [153, 169, 182]],

       [[108, 119, 127],
        [110, 123, 131],
        [118, 128, 138],
        ...,
        [156, 169, 183],
        [155, 168, 182],
        [154, 167, 181]],

       ...,

       [[162, 186, 198],
        [157, 181, 193],
        [142, 166, 178],
        ...,
        [181, 204, 206],
        [170, 193, 195],
        [149, 172, 174]],

       [[140, 164, 176],
        [147, 171, 183],
        [139, 163, 175],
        ...,
        [169, 187, 188],
        [125, 143, 144],
        [106, 124, 125]],

       [[154, 178, 190],
        [154, 178, 190],
        [121, 145, 157],
        ...,
        [183, 198, 200],
        [128, 143, 145],
        [127, 142, 144]]

In [3]:
#图像的显示,也可以创建多个窗口
cv2.imshow('image',img) 
# 等待时间，毫秒级，0表示任意键终止
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [4]:
def cv_show(name,img):
    cv2.imshow(name,img) 
    cv2.waitKey(0) 
    cv2.destroyAllWindows()

In [5]:
# 图片形状 (H x W X C)
img.shape

(414, 500, 3)

In [6]:
# 转换图片颜色通道 BGR -> 灰色
img=cv2.imread('cat.jpg',cv2.IMREAD_GRAYSCALE)
img

array([[153, 157, 162, ..., 174, 173, 172],
       [119, 124, 129, ..., 173, 172, 171],
       [120, 124, 130, ..., 172, 171, 170],
       ...,
       [187, 182, 167, ..., 202, 191, 170],
       [165, 172, 164, ..., 185, 141, 122],
       [179, 179, 146, ..., 197, 142, 141]], dtype=uint8)

In [7]:
img.shape

(414, 500)

In [8]:
#图像的显示,也可以创建多个窗口
cv2.imshow('image',img) 
# 等待10000毫秒（10秒）自动关闭
cv2.waitKey(10000) 
cv2.destroyAllWindows()

In [9]:
# 保存转换的灰色图片
cv2.imwrite('mycat.png',img)

True

In [10]:
# 查询图片类型
type(img)

numpy.ndarray

In [11]:
# 图片大小
img.size

207000

In [12]:
# img中的数据类型 (uint8：仅表示非负数，范围0~255，正好符合RGB像素值)
img.dtype

dtype('uint8')

### 数据读取-视频

- cv2.VideoCapture可以捕获摄像头，用数字来控制不同的设备，例如0,1。
- 如果是视频文件，直接指定好路径即可。

In [33]:
vc = cv2.VideoCapture('test.mp4')

In [34]:
# 检查是否打开正确
if vc.isOpened(): 
    # vc.raad()会逐帧读取视频 open为是否可以读取到该帧，frame代表读取到该帧对应的图片
    oepn, frame = vc.read()
else:
    open = False

In [35]:
# 播放视频其实是循环遍历每一帧的图片
while open:
    ret, frame = vc.read()
    if frame is None:
        break
    if ret == True:
        # 将BGR图像转换为灰色图像
        gray = cv2.cvtColor(frame,  cv2.COLOR_BGR2GRAY)
        # 展示图像
        cv2.imshow('result', gray)
        if cv2.waitKey(100) & 0xFF == 27:
            break
# 销毁窗口，关闭视频
vc.release()
cv2.destroyAllWindows()

### 截取部分图像数据

In [37]:
img=cv2.imread('cat.jpg')
# 截取一部分高和宽
cat=img[0:50,0:200] 
cv_show('cat',cat)

### 颜色通道提取

In [38]:
# 拆开BGR三基色通道
b,g,r=cv2.split(img)

In [39]:
r

array([[160, 164, 170, ..., 185, 184, 183],
       [126, 131, 137, ..., 184, 183, 182],
       [127, 131, 138, ..., 183, 182, 181],
       ...,
       [198, 193, 178, ..., 206, 195, 174],
       [176, 183, 175, ..., 188, 144, 125],
       [190, 190, 157, ..., 200, 145, 144]], dtype=uint8)

In [40]:
r.shape

(414, 500)

In [49]:
# 合并三基色通道，注意合并顺序[b,g,r]，合并出一张BGR彩色图片
img=cv2.merge((b,g,r))
img.shape

(414, 500, 3)

In [50]:
# 只保留R
cur_img = img.copy()
cur_img[:,:,0] = 0
cur_img[:,:,1] = 0
cv_show('R',cur_img)



In [51]:
# 只保留G
cur_img = img.copy()
cur_img[:,:,0] = 0
cur_img[:,:,2] = 0
cv_show('G',cur_img)

In [52]:
# 只保留B
cur_img = img.copy()
cur_img[:,:,1] = 0
cur_img[:,:,2] = 0
cv_show('B',cur_img)

### 边界填充

In [ ]:
# 指定上下左右分别填充的大小
top_size,bottom_size,left_size,right_size = (50,50,50,50)

# 复制法，无线复制边缘像素点进行填充
replicate = cv2.copyMakeBorder(img, top_size, bottom_size, left_size, right_size, borderType=cv2.BORDER_REPLICATE)
# 反射法：以图像边缘进行像素点反射填充
reflect = cv2.copyMakeBorder(img, top_size, bottom_size, left_size, right_size,cv2.BORDER_REFLECT)
# 反射法：和上边的类似
reflect101 = cv2.copyMakeBorder(img, top_size, bottom_size, left_size, right_size, cv2.BORDER_REFLECT_101)
# 外包装法
wrap = cv2.copyMakeBorder(img, top_size, bottom_size, left_size, right_size, cv2.BORDER_WRAP)
# 常量法：使用常量数值进行填充
constant = cv2.copyMakeBorder(img, top_size, bottom_size, left_size, right_size,cv2.BORDER_CONSTANT, value=0)

In [ ]:
import matplotlib.pyplot as plt
plt.subplot(231), plt.imshow(img, 'gray'), plt.title('ORIGINAL')
plt.subplot(232), plt.imshow(replicate, 'gray'), plt.title('REPLICATE')
plt.subplot(233), plt.imshow(reflect, 'gray'), plt.title('REFLECT')
plt.subplot(234), plt.imshow(reflect101, 'gray'), plt.title('REFLECT_101')
plt.subplot(235), plt.imshow(wrap, 'gray'), plt.title('WRAP')
plt.subplot(236), plt.imshow(constant, 'gray'), plt.title('CONSTANT')

plt.show()

- BORDER_REPLICATE：复制法，也就是复制最边缘像素。
- BORDER_REFLECT：反射法，对感兴趣的图像中的像素在两边进行复制例如：fedcba|abcdefgh|hgfedcb   
- BORDER_REFLECT_101：反射法，也就是以最边缘像素为轴，对称，gfedcb|abcdefgh|gfedcba
- BORDER_WRAP：外包装法cdefgh|abcdefgh|abcdefg  
- BORDER_CONSTANT：常量法，常数值填充。

### 数值计算

In [ ]:
img_cat=cv2.imread('cat.jpg')
img_dog=cv2.imread('dog.jpg')

In [ ]:
# 针对该图片每个位置都加上10，如果累加之后超过255，那么就需要计算 【相加后的数字 % 256 】这个余数就是最终的累加结果
img_cat2= img_cat +10 
# 截取数据，便于展示
img_cat[:5,:,0]

In [ ]:
img_cat2[:5,:,0]

In [ ]:
# 直接相加图片也是将对应像素点的值进行相加。超过255，使用 %256 计算最终的累加结果
(img_cat + img_cat2)[:5,:,0] 

In [ ]:
# add()函数和直接相加区别在于，使用add()函数不会执行 %256 ，累加超过255直接保存最大值255
cv2.add(img_cat,img_cat2)[:5,:,0]

### 图像融合

In [ ]:
# 这两个图片不能直接相加进行融合，因为两张图的高宽通道维度不一样
# 只有当两张照片维度一致时才可以进行直接相加
img_cat + img_dog

In [ ]:
img_cat.shape

In [ ]:
# 将狗图片的三维重置为和猫一样
img_dog = cv2.resize(img_dog, (500, 414))
img_dog.shape

In [ ]:
# 猫图片比重占百分之四十，狗占用百分之六十，偏置设置为0
res = cv2.addWeighted(img_cat, 0.4, img_dog, 0.6, 0)

In [ ]:
plt.imshow(res)

In [ ]:
# 按照倍速进行大小重置 (0,0)代表不直接指定高度和宽度，fx=4代表将宽度变为4倍，fy代表将高度变为4倍
res = cv2.resize(img, (0, 0), fx=4, fy=4)
plt.imshow(res)

In [ ]:
# fx=1代表宽度不变 fy=3代表高度变为3倍
res = cv2.resize(img, (0, 0), fx=1, fy=3)
plt.imshow(res)